version: '3.8'


services:
  db:
    image: postgres:16
    container_name: itsupp_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-itsupp_db}
      POSTGRES_USER: ${POSTGRES_USER:-itsupp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
    ports:
      - "${DB_PORT_MAPPING:-5436:5432}"
    volumes:
      - itsupp_postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: itsupp_app
    restart: always
    depends_on:
      - db
    ports:
      - "${APP_PORT_MAPPING:-8443:8443}"
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB:-itsupp_db}
      DB_USER: ${POSTGRES_USER:-itsupp_user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}


volumes:
  itsupp_postgres_data: