services:
  db:
    image: postgres:16
    container_name: ziovpo_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - ziovpo_postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ziovpo_app
    restart: always
    depends_on:
      - db
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_DAYS: ${JWT_REFRESH_DAYS}
      SIGNATURE_KEYSTORE_PATH: ${SIGNATURE_KEYSTORE_PATH}
      SIGNATURE_KEYSTORE_TYPE: ${SIGNATURE_KEYSTORE_TYPE}
      SIGNATURE_KEY_ALIAS: ${SIGNATURE_KEY_ALIAS}
      SIGNATURE_KEY_PASSWORD: ${SIGNATURE_KEY_PASSWORD}
      SIGNATURE_ALGORITHM: ${SIGNATURE_ALGORITHM}

volumes:
  ziovpo_postgres_data: