package com.example.ziovpo.signature;

public enum SignatureErrorCode {
    INPUT_INVALID,
    CANONICALIZATION_FAILED,
    OUTPUT_ENCODING_FAILED,
    KEY_SOURCE_UNAVAILABLE,
    AUTH_FAILED,
    KEY_NOT_FOUND,
    KEY_FORMAT_INVALID,
    CANONICALIZATION_ERROR,
    KEY_PROVIDER_ERROR,
    SIGN_OPERATION_FAILED
}
