name: rbpo ci/cd

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Decode Keystore
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > src/main/resources/keystore.p12

      - name: Test and Build with Maven
        run: ./mvnw -B clean verify
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Save Public Certificate
        run: |
          echo "${{ vars.PUBLIC_KEY_CERT }}" > /tmp/cert.pem

      - name: Verify Public Key
        run: |
          openssl x509 -in /tmp/cert.pem -text -noout | grep -E "Subject:|CN=|Public-Key:"

      - name: Verify Signature Algorithm
        run: |
          openssl x509 -in /tmp/cert.pem -text -noout | grep -A2 "Signature"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ziovpo-app-jar
          path: target/*.jar